version: '3.4'

services:
  catalog.api:
    build: 
      context: ./
      dockerfile: Catalog.Api/Dockerfile
    environment:
      ConnectionString: Server=sql.data;Initial Catalog=CatalogDb;User Id=sa;Password=Pass@word
      EventBusConnection: rabbitmq
    depends_on:
      - sql.data
      - rabbitmq
    ports:
      - 32770:80
  basket.api:
    build:
      context: ./
      dockerfile: Basket.API/Dockerfile
    environment:
      EventBusConnection: rabbitmq
    depends_on:
      - rabbitmq
  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: Pass@word
      ACCEPT_EULA: Y
    ports:
      - 5434:1433
  baset.data:
    image: redis
    expose:
      - 6379
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672