version: '3.4'

services:
  catalog.api:
    build: 
      context: ./
      dockerfile: Catalog.Api/Dockerfile
    environment:
      ConnectionString: Server=sql.data;Initial Catalog=CatalogDb;User Id=sa;Password=Pass@word
    depends_on:
      - sql.data
  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: Pass@word
      ACCEPT_EULA: Y
    ports:
      - 5434:1433
  baset.data:
    image: redis
    expose:
      - 6379