version: '3.4'

services:
  catalog.api:
    build: ./Catalog.Api
    environment:
      ConnectionString: Server=tcp:localhost,5433;Initial Catalog=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word
    ports:
      - 5001:80
    depends_on:
      - sql.data
  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: Pass@word
      ACCEPT_EULA: Y
    ports:
      - 5434:1433